# TASK 2 - IRIS FLOWER CLASSIFICATION

In [3]:
# IMPORTING THE NECESSARY PACKAGES :

import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [5]:
# LOADING THE DATASET

df = pd.read_csv(r"C:\Users\mohamed malhan\Desktop\ml\iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
#CHANGING THE NAMES OF THE COLUMNS:

df = df.rename(columns={'SepalLengthCm':'sl', 'SepalWidthCm':'sw', 'PetalLengthCm':'pl', 'PetalWidthCm':'pw'})

In [7]:
# We can see that there are three different types of Iris flowers

df['Species'].value_counts()

Iris-setosa        50
Iris-virginica     50
Iris-versicolor    50
Name: Species, dtype: int64

In [8]:
# Statistical details of the dataset :

df.describe()

Id          sl          sw          pl          pw
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean    75.500000    5.843333    3.054000    3.758667    1.198667
std     43.445368    0.828066    0.433594    1.764420    0.763161
min      1.000000    4.300000    2.000000    1.000000    0.100000
25%     38.250000    5.100000    2.800000    1.600000    0.300000
50%     75.500000    5.800000    3.000000    4.350000    1.300000
75%    112.750000    6.400000    3.300000    5.100000    1.800000
max    150.000000    7.900000    4.400000    6.900000    2.500000

In [9]:
# There are no null values in the dataset and the data types are known :

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Id       150 non-null    int64  
 1   sl       150 non-null    float64
 2   sw       150 non-null    float64
 3   pl       150 non-null    float64
 4   pw       150 non-null    float64
 5   Species  150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [10]:
# The dependent and independent(Target variable) are asigned as x and y respectively

x = df.iloc[:,:4]
y = df.iloc[:,5]

In [11]:
x , y

(      Id   sl   sw   pl
 0      1  5.1  3.5  1.4
 1      2  4.9  3.0  1.4
 2      3  4.7  3.2  1.3
 3      4  4.6  3.1  1.5
 4      5  5.0  3.6  1.4
 ..   ...  ...  ...  ...
 145  146  6.7  3.0  5.2
 146  147  6.3  2.5  5.0
 147  148  6.5  3.0  5.2
 148  149  6.2  3.4  5.4
 149  150  5.9  3.0  5.1
 
 [150 rows x 4 columns],
 0         Iris-setosa
 1         Iris-setosa
 2         Iris-setosa
 3         Iris-setosa
 4         Iris-setosa
             ...      
 145    Iris-virginica
 146    Iris-virginica
 147    Iris-virginica
 148    Iris-virginica
 149    Iris-virginica
 Name: Species, Length: 150, dtype: object)

In [12]:
# Splitting the Training and Testing data 

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.4,random_state =1)

# Random Forest Classifier - Model

In [13]:
# Creating a RandomForestClassifier model and fitting it with Training data

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(max_depth =6 , random_state=123 , criterion='entropy')
model.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', max_depth=6, random_state=123)

In [14]:
# Predicting with the Test data

y_pred = model.predict(x_test)
y_pred


array(['Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa

In [26]:
# By the Classification report it is obvious that the precision ,recall , f1-score are exactly '1' 
# The confusion matrix and the count of test data shows that all the individual types have been segrigated in a correct way

print(classification_report(y_test,y_pred))
print()
print(confusion_matrix(y_test,y_pred))
print()
y_test.value_counts()

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       1.00      1.00      1.00        21
 Iris-virginica       1.00      1.00      1.00        20

       accuracy                           1.00        60
      macro avg       1.00      1.00      1.00        60
   weighted avg       1.00      1.00      1.00        60


[[19  0  0]
 [ 0 21  0]
 [ 0  0 20]]



Iris-versicolor    21
Iris-virginica     20
Iris-setosa        19
Name: Species, dtype: int64

In [42]:
# The Full Accuracy score shows that the Random Forest model is best fit for the dataset

accuracy_score(y_test,y_pred)

1.0